namespace org.hamsaqua.event.payment.authorize.v1.authorize.result;

schema EventType;

enum EventType {
	AUTHORIZE_RESULT
}

enum AuthorizeStatus {
	APPROVED,
	DECLINED,
	ERROR
}

record AuthorizeResultV1 {
	EventType eventType;
	@logicalType("uuid") string transactionId;
	@logicalType("uuid") string correlationId;
	AuthorizeStatus status;
	string? authorizeCode = null;
	string? reason = null;
	string issuer;
	double? amount = null;
	string? currency = null;
	@logicalType("timestamp-millis") long timestamp;
}
