name: Publish REST
on:
  push:
    branches: [ main ]
    paths: [ "rest" ]
jobs:
  detect:
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            rest
      - uses: tj-actions/changed-files@v47
        with:
          base_branch: main
        id: changed
      - uses: ${{ vars.REPO_SCRIPT }}/.github/actions/${{ vars.SCRIPT_DETECT }}@main
        with:
          changed: ${{ toJSON(steps.changed.outputs.all_changed_files) }}
        id: matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    runs-on: ubuntu-latest
  publish:
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            ${{ matrix.based }}/${{ matrix.spec }}.yaml
            *.gradle.kts
            gradle/
            gradlew
      - uses: ${{ vars.REPO_ACTION }}/.github/actions/${{ vars.ACTION_REST }}@main
        with:
          domain: "payment"
          usecase: "authorize"
          version: "v1"
          spec: ${{ matrix.spec }}
          tld: ${{ vars.TLD }}
          org: ${{ vars.ORG }}
          contract_repo: ${{ vars.REPO_CONTRACT }}
          artifact_repo: ${{ vars.REPO_ARTIFACT }}
          dispatch: ${{ vars.DISPATCH_REST }}
          contract_pat: ${{ secrets.PAT_CONTRACT }}
          artifact_pat: ${{ secrets.PAT_ARTIFACT }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.matrix) }}
    needs: detect
    runs-on: ubuntu-latest
